### ISSUE TITLE
ediss: harvested 7200 records but only 7199 records present in Solr and OpenRefine

### ISSUE THREAD

**Issue by felixlohmeier** [subhh/HOS-MetadataTransformations#5]
There is one record in ediss that has no URN:

> Das Dispositiv der Zukunftsfähigen Entwicklung
> http://ediss.sub.uni-hamburg.de/volltexte/2006/2889/

Current transformation rules for ediss rely on the assumption that every record has a urn in field dc:identifier.

**Comment by jfmaas** [comment]
That's actually not an issue with the metadata transformation but an error in subhh/ediss... All the documents in ediss must have an URN to be elegible for the long term archiving of the DNB.
